name: Codegen

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  compare_schemas:
    name: Comparing schemas
    runs-on: ubuntu-latest

    outputs:
      need_regenerate: ${{ steps.cmp.outputs.need_regenerate }}

    steps:
      - uses: actions/checkout@v2

      - name: Download schema from external URL
        run: curl https://api.refactr.it/v1/spec -o new_schema.json

      - name: Compare specs
        id: cmp
        if: ${{ hashFiles('./new_schema.json') != hashFiles('./spec/schema.json') }}
        run: |
          echo "::set-output name=need_regenerate::1"

  codegen:
    name: Generating code
    needs: compare_schemas
    runs-on: ubuntu-latest

    if: ${{ needs.compare_schemas.outputs.need_regenerate == '1' }}

    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GEN_DEPLOY_KEY1 }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installing Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
          java-package: jdk

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install OpenAPI generator
        run: npm install @openapitools/openapi-generator-cli@^2 -g

      - name: Installing dependencies
        run: npm install

      - name: Download schema from external URL
        run: npm run fetch

      - name: Generating OpenAPI client
        run: npm run generate

      - name: Push changes to the repository
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b ${{ github.ref_name }}-codegen
          git add .
          git commit -am "Update schema with ${{ github.workflow }}"
          git push -u https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
