name: Codegen

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  compare_schemas:
    name: Comparing schemas
    runs-on: ubuntu-latest

    outputs:
      need_regenerate: ${{ steps.cmp.outputs.need_regenerate }}

    steps:
      - uses: actions/checkout@v3

      - name: Download schema from external URL
        run: -|
          curl https://api.us-west-2.factory.sophos.com/v1/spec | jq '.' > new_api.json
          curl https://auth.us-west-2.factory.sophos.com/v1/spec | jq '.' > new_authApi.json

      - name: Compare specs
        id: cmp
        if: ${{ hashFiles('./new_api.json') != hashFiles('./spec/api.json') || hashFiles('./new_authApi.json') != hashFiles('./spec/authApi.json') }}
        run: |
          echo "need_regenerate=1" >> $GITHUB_OUTPUT

  codegen:
    name: Generating code
    needs: compare_schemas
    runs-on: ubuntu-latest
    permissions: write-all

    if: ${{ needs.compare_schemas.outputs.need_regenerate == '1' }}

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GEN_DEPLOY_KEY1 }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installing Java
        uses: actions/setup-java@v3
        with:
          java-version: 12.x
          java-package: jdk
          distribution: adopt

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install OpenAPI generator
        run: npm install @openapitools/openapi-generator-cli@^2 -g

      - name: Installing dependencies
        run: npm install

      - name: Download schema from external URL
        run: npm run fetch

      - name: Generating OpenAPI client
        run: npm run generate

      - name: Making a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update client
          title: Update client
          body: |
            This is an automatically generated PR for updating the specification schema. (`gen.yml`)
          assignees: sophos-rickc, marcfieser
          reviewers: sophos-rickc, marcfieser
