name: Generate pre-release code

on:
  workflow_dispatch:

jobs:
  compare_schemas:
    name: Comparing schemas
    runs-on: ubuntu-latest

    outputs:
      need_regenerate: ${{ steps.cmp.outputs.need_regenerate }}

    steps:
      - uses: actions/checkout@v2

      - name: Download schema from the main API
        run: curl https://api.staging.factory.sophos.com/v1/spec -o new_schema.json

      - name: Compare specs
        id: cmp
        if: ${{ hashFiles('./new_schema.json') != hashFiles('./spec/schema.json') }}
        run: |
          echo "::set-output name=need_regenerate::1"

  codegen:
    name: Generating code
    needs: compare_schemas
    runs-on: ubuntu-latest
    permissions: write-all

    if: ${{ needs.compare_schemas.outputs.need_regenerate == '1' }}

    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GEN_DEPLOY_KEY1 }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installing Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
          java-package: jdk

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install OpenAPI generator
        run: npm install @openapitools/openapi-generator-cli@^2 -g

      - name: Installing dependencies
        run: npm install

      - name: Download schema from external URL
        run: mkdir -p spec && curl -s https://api.staging.factory.sophos.com/v1/spec | jq '.' > ./spec/schema.json

      - name: Generating OpenAPI client
        run: npm run generate

      - name: Making a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update client
          title: Update client
          body: |
            This PR contains changes generated against the development API.
          assignees: sophos-victoria
          reviewers: sophos-victoria
